name: aunkur_farmer
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Network Package
  dio: ^5.9.0
  connectivity_plus: ^7.0.0

  #  Local Storage
  shared_preferences: ^2.5.3
  sqflite: ^2.3.2

  # State Management
  flutter_bloc: ^9.1.1
  rxdart: ^0.28.0
  equatable: ^2.0.7

  # UI
  flutter_svg: ^2.2.1
  convex_bottom_bar: ^3.2.0
  font_awesome_flutter: ^10.6.0
  pin_code_fields: ^8.0.1
  lottie: ^3.3.2
  flutter_rating: ^2.0.2

  # Utils
  google_fonts: ^6.3.2
  get_it: ^8.2.0
  permission_handler: ^12.0.1
  intl_utils: ^2.8.10
  cached_network_image: ^3.4.1
  flutter_cache_manager: ^3.4.1
  in_app_review: ^2.0.11
  url_launcher: ^6.3.2
  flutter_html: ^3.0.0
  device_info_plus: ^12.1.0
  geolocator: ^14.0.2
  path_provider: ^2.0.9


  # Firebase Packages
  firebase_core: ^4.1.1
  firebase_messaging: ^16.0.2

  # For Local Notifications
  flutter_local_notifications: ^19.4.2

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/image/
    - assets/json/
    - assets/svg/
    - assets/lang/

flutter_intl:
  enabled: true
